# Generated by Django 2.2.7 on 2021-12-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='house_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbhost.House_main'),
        ),
    ]
