# Generated by Django 2.2.7 on 2021-12-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0004_auto_20211205_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
