# Generated by Django 2.2.7 on 2021-12-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0006_auto_20211208_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(default=None),
        ),
    ]
