# Generated by Django 2.2.7 on 2021-12-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0008_auto_20211209_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_main',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
