# Generated by Django 2.2.7 on 2021-12-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0009_house_main_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_main',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
