# Generated by Django 2.2.7 on 2021-12-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0010_auto_20211209_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_detail',
            name='number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
