# Generated by Django 2.2.7 on 2021-12-10 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0014_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
