# Generated by Django 2.2.7 on 2021-12-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0015_question_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('question_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbhost.Question')),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
