# Generated by Django 2.2.7 on 2021-12-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0017_auto_20211210_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
