# Generated by Django 2.2.7 on 2021-12-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhost', '0018_review_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_main',
            name='location_1',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house_main',
            name='location_2',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house_main',
            name='location_3',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house_main',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
